#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /  
    controller: App\Controller\WebController::home

productos:
    path: /productos
    controller: App\Controller\WebController::productos

politicas:
    path: /politicas
    controller: App\Controller\WebController::politicas


nosotros:
    path: /nosotros
    controller: App\Controller\WebController::nosotros


contactenos:
    path: /contactenos
    controller: App\Controller\WebController::contactenos
